# permissions for end users to edit zoneawareupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zoneawareupdate-editor-role
rules:
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates/status
  verbs:
  - get
