# permissions for end users to view zonedisruptionbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zonedisruptionbudget-viewer-role
rules:
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zonedisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zonedisruptionbudgets/status
  verbs:
  - get
