# permissions for end users to view zoneawareupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zoneawareupdate-viewer-role
rules:
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zonecontrol.k8s.aws
  resources:
  - zoneawareupdates/status
  verbs:
  - get
